version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - ksboot-network

volumes:
  redis_data:
    driver: local

networks:
  ksboot-network:
    driver: bridge
